version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/thomas-fire-help
    ports:
      - "3000:3000"
    depends_on:
      - db
  webpack:
    build: .
    command: bin/webpack-dev-server
    environment:
      - RAILS_ENV=development
    volumes:
      - .:/thomas-fire-help
    ports:
      - "3035:3035"
