default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  host: <%= ENV.fetch("HEROKU_POSTGRESQL_BLUE_URL", 'localhost') %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  pool: 5

development:
  <<: *default
  database: fire_help_api_development

test:
  <<: *default
  database: fire_help_api_test

production:
  <<: *default
  database: production
