default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV.fetch("DB_USERNAME", "") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  pool: 5

development:
  <<: *default
  database: thomas_fire_help_development

test:
  <<: *default
  database: thomas_fire_help_test

production:
  <<: *default
  database: production
