default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  host: <%= ENV.fetch("DB_HOST", 'localhost') %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  pool: 5

development:
  <<: *default
  database: thomas_fire_help_development

test:
  <<: *default
  database: thomas_fire_help_test

production:
  <<: *default
  database: production
