default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  pool: 5
  
development:
  <<: *default
  database: thomas_fire_help_development

test:
  <<: *default
  database: thomas_fire_help_test

production:
  <<: *default
  database: production
