default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_URL", 'localhost') %>
  pool: 5

development:
  <<: *default
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  database: fire_help_api_development

test:
  <<: *default
  database: fire_help_api_test

production:
  <<: *default
  database: production
  host: <%= ENV["HEROKU_POSTGRESQL_BLUE_URL"] %>
